/**
 * ShoppingListApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param id 
 * @param name 
 * @param qtt 
 * @param isChecked 
 */
data class Product (

    val id: kotlin.String? = null,
    val name: kotlin.String? = null,
    val qtt: kotlin.Int? = null,
    val isChecked: kotlin.Boolean? = null
) {
}